# Chapter 14: Scipy

**Scipy** is a collection of mathematical and statistical tools built on Numpy.  Tools include various representations for rotations, as well as clustering, interpolation, sparse arrays, and statistical distributions.   Documentation is available here: [https://docs.scipy.org/doc/scipy/tutorial/general.html](https://docs.scipy.org/doc/scipy/tutorial/general.html).  

For installation, see [Chapter 13](Chapter_13_Numpy.ipynb).

## Rotations with Scipy

Common operations we will need are to translate and rotate 3D points.  We've seen point translation with Numpy arrays in Chapter 13.  Rotation are a bit tricker and there are multiple ways they can be represented.  Scipy has a rotation class that can read in rotations defined in multiple formats including Euler angles, rotation matrices and quaternions.  Its internal representation is hidden, but it can display a rotation in any of these formats.  Official documentation is [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html?highlight=rotation#scipy.spatial.transform.Rotation).  Let's try it out.

First, we represent 3D points as stacked vectors in 2D Numpy arrays like this:

In [12]:
import numpy as np
points = np.array([[5., 2., 0.], [4., 2., 2.], [4., 2., 2.], [5., 2., 0.]])
points

array([[5., 2., 0.],
       [4., 2., 2.],
       [4., 2., 2.],
       [5., 2., 0.]])

Now let's create a rotation:

In [13]:
from scipy.spatial.transform import Rotation as R
rot = R.from_euler('XYZ',[0,0,45],degrees=True)     # A 45-degree rotation around the z axis
rot

The internal rotation representation is hidden, but we can view the rotation in various representations like this:

In [14]:
rot.as_euler('XYZ')

array([0.        , 0.        , 0.78539816])

In [15]:
rot.as_matrix()

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

To actually rotate points, we could extract a rotation matrix and multiply a 2D array of points like this:

In [20]:
rpoints = np.matmul( rot.as_matrix(), points.T ).T
rpoints

array([[2.12132034, 4.94974747, 0.        ],
       [1.41421356, 4.24264069, 2.        ],
       [1.41421356, 4.24264069, 2.        ],
       [2.12132034, 4.94974747, 0.        ]])

Here we have used the Numpy `matmul()` function to do matrix multiplication.  We've also applied `.T` to the `point_array` to transpose it so that points are columns before we multiply by `rot`, and then transposed it back into row format.

Now a simpler and much preferred way to rotate the points is to let the Scipy class itself apply the rotation to the raw point array like this:

In [22]:
rpoints = rot.apply(points)
rpoints

array([[2.12132034, 4.94974747, 0.        ],
       [1.41421356, 4.24264069, 2.        ],
       [1.41421356, 4.24264069, 2.        ],
       [2.12132034, 4.94974747, 0.        ]])

This returns a rotated copy of the points.   

___
### [Outline](../README.md), Next: [Chapter 15: OpenCV](Chapter_15_OpenCV.ipynb)